In [21]:
from CQS.methods import Hamiltonian, Cartan, FindParameters
import numpy as np
from CQS.util.verification import exactU, Nident, PauliExpUnitary, KHK


In [22]:

ham = Hamiltonian(2, [(1, 'tfim', False)])
cartan = Cartan(ham, involution='countY')
cartan.subAlgebra([(1,0)])
params = FindParameters(cartan, optimizerMethod='Lax')
print(params.cartan.m)
print(params.cartan.h)
params2 = FindParameters(cartan)
print(params2.kCoefs, params2.hCoefs)


[ 4.94065646e-324  4.94065646e-324 -6.18033694e-001  1.61803369e+000
  5.08610983e-001  5.08610983e-001]
--- 0.1477949619293213 seconds ---
[(1, 0), (0, 1), (3, 3), (2, 2)]
[(1, 0), (0, 1)]
Optimization terminated successfully.
         Current function value: -1.705543
         Iterations: 6
         Function evaluations: 9
         Gradient evaluations: 9
--- 0.005706310272216797 seconds ---
Optimization Error:
8.339270698652428e-15
[-1.06218532 -0.27678721] [(-1.6180339887498913+0j), (-0.6180339887498971+0j)]


In [ ]:
U = exactU(ham.HCoefs, ham.HTuples, 1)

In [ ]:
import numpy as np
from numpy import kron
from scipy.linalg import expm, norm

import CQS.util.IO as IO


def KHKtypeI(kCoefs, hCoefs, k, h):
    N = len(h[0])
    KHK = Nident(N)

    #First loop of K terms:
    K = expm(PauliSum(1j*kCoefs, k))
    KHK = KHK @ K

    #H terms
    for (term, co) in zip(h, hCoefs):
        KHK = KHK @ PauliExpUnitary(N, co, term)

    K = expm(PauliSum(-1j*kCoefs, k))
    KHK = KHK @ K
    return KHK


def PauliSum(coefficients, tuples):
    H = np.diag(np.zeros(2**len(tuples[0])))

    for (co, term) in zip(coefficients, tuples):
        print(co)
        print(term)
        H = H + IO.tuplesToMatrix(co, term)
    return H


In [ ]:
#KHK = KHKtypeI(params.kCoefs, params.hCoefs,
#params.cartan.k, params.cartan.h)
print((params.kCoefs, params.hCoefs))
KHKval = KHK(params.kCoefs, params.hCoefs, params.cartan.k, params.cartan.h)

(array([6.00639812, 0.50861098]), array([1.28643669e-174, 1.28643669e-174]))


In [ ]:
KHKval


array([[ 1.00000000e+00-2.01163804e-183j,
        -1.37549129e-17-1.28643669e-174j,
        -2.83374819e-17+1.28643669e-174j,
         5.87122117e-18+2.01163803e-183j],
       [-1.38533168e-17-1.28643669e-174j,
         1.00000000e+00+2.01163804e-183j,
        -5.36829518e-18-2.01163803e-183j,
         2.83374819e-17+1.28643669e-174j],
       [ 5.75123489e-17+1.28643669e-174j,
         5.87122117e-18-2.01163798e-183j,
         1.00000000e+00+2.01163803e-183j,
         1.37549129e-17-1.28643669e-174j],
       [-5.36829518e-18+2.01163792e-183j,
        -5.75123489e-17+1.28643669e-174j,
         1.38533168e-17-1.28643669e-174j,
         1.00000000e+00-2.01163803e-183j]])

In [ ]:
U

array([[-3.84852853e-02+0.59665795j,  7.06115200e-17+0.35184491j,
         1.08789163e-17+0.35184491j, -5.78787591e-01-0.24481304j],
       [ 2.81552897e-17+0.35184491j, -3.84852853e-02-0.59665795j,
        -5.78787591e-01+0.24481304j, -4.77003567e-17+0.35184491j],
       [ 1.50926397e-17+0.35184491j, -5.78787591e-01+0.24481304j,
        -3.84852853e-02-0.59665795j,  1.77273529e-17+0.35184491j],
       [-5.78787591e-01-0.24481304j,  4.97853916e-17+0.35184491j,
         9.64493029e-18+0.35184491j, -3.84852853e-02+0.59665795j]])