In [1]:
from CQS.methods import Hamiltonian, Cartan, FindParameters
import numpy as np
from CQS.util.verification import exactU, Nident, PauliExpUnitary, KHK


In [2]:

ham = Hamiltonian(2, [(1, 'tfim', False)])
cartan = Cartan(ham, involution='countY')
params = FindParameters(cartan, optimizerMethod='Lax')
params2 = FindParameters(cartan)
print(params2.kCoefs, params2.hCoefs)


[(3, 3), (2, 2), (1, 0), (0, 1)]
[(2, 3), (3, 2)]
[[-2.  1.]
 [ 2.  0.]]
[1. 0. 1. 1. 0. 0.]
[ 1.28643924e-174  1.28643924e-174  6.18033922e-001  1.61803390e+000
 -2.00200000e+002  2.00200000e+002]
--- 0.12548232078552246 seconds ---
Optimization terminated successfully.
         Current function value: -0.388932
         Iterations: 5
         Function evaluations: 6
         Gradient evaluations: 6
--- 0.0044384002685546875 seconds ---
Optimization Error:
1.408409672457071e-14
[0.508611 0.508611] [(-0.6180339887498917+0j), (1.6180339887498916+0j)]


In [3]:
U = exactU(ham.HCoefs, ham.HTuples, 1)

In [4]:
import numpy as np
from numpy import kron
from scipy.linalg import expm, norm

import CQS.util.IO as IO


def KHKtypeI(kCoefs, hCoefs, k, h):
    N = len(h[0])
    KHK = Nident(N)

    #First loop of K terms:
    K = expm(PauliSum(1j*kCoefs, k))
    KHK = KHK @ K

    #H terms
    for (term, co) in zip(h, hCoefs):
        KHK = KHK @ PauliExpUnitary(N, co, term)

    K = expm(PauliSum(-1j*kCoefs, k))
    KHK = KHK @ K
    return KHK


def PauliSum(coefficients, tuples):
    H = np.diag(np.zeros(2**len(tuples[0])))

    for (co, term) in zip(coefficients, tuples):
        print(co)
        print(term)
        H = H + IO.tuplesToMatrix(co, term)
    return H


In [5]:
#KHK = KHKtypeI(params.kCoefs, params.hCoefs,
#params.cartan.k, params.cartan.h)
KHKval = KHK(-1*params.kCoefs, params.hCoefs, params.cartan.k, params.cartan.h)

In [6]:
KHKval


array([[ 1.00000000e+00-1.22663013e-174j,
         4.84172943e-17+3.87691173e-175j,
         2.23308906e-17-3.87691173e-175j,
         1.30327845e-17+1.22663013e-174j],
       [-2.35704120e-17+3.87691173e-175j,
         1.00000000e+00+1.22663013e-174j,
         4.25736985e-17-1.22663013e-174j,
        -2.23308906e-17-3.87691173e-175j],
       [ 2.23308906e-17-3.87691173e-175j,
         1.30327845e-17-1.22663013e-174j,
         1.00000000e+00+1.22663013e-174j,
        -4.84172943e-17+3.87691173e-175j],
       [ 4.25736985e-17+1.22663013e-174j,
        -2.23308906e-17-3.87691173e-175j,
         2.35704120e-17+3.87691173e-175j,
         1.00000000e+00-1.22663013e-174j]])

In [7]:
U

array([[-3.84852853e-02+0.59665795j,  7.06115200e-17+0.35184491j,
         1.08789163e-17+0.35184491j, -5.78787591e-01-0.24481304j],
       [ 2.81552897e-17+0.35184491j, -3.84852853e-02-0.59665795j,
        -5.78787591e-01+0.24481304j, -4.77003567e-17+0.35184491j],
       [ 1.50926397e-17+0.35184491j, -5.78787591e-01+0.24481304j,
        -3.84852853e-02-0.59665795j,  1.77273529e-17+0.35184491j],
       [-5.78787591e-01-0.24481304j,  4.97853916e-17+0.35184491j,
         9.64493029e-18+0.35184491j, -3.84852853e-02+0.59665795j]])