In [ ]:
from CQS.methods import Hamiltonian, Cartan, FindParameters
import numpy as np
from CQS.util.verification import exactU, Nident, PauliExpUnitary, KHK


In [ ]:

ham = Hamiltonian(2, [(1, 'tfim', False)])
cartan = Cartan(ham, involution='countY')
cartan.subAlgebra([(1,0)])
params = FindParameters(cartan, optimizerMethod='Lax')
print(params.cartan.m)
print(params.cartan.h)
params2 = FindParameters(cartan)
print(params2.kCoefs, params2.hCoefs)


[[2. 1.]
 [2. 0.]]
[[[ 2.  2.]
  [-2.  3.]]

 [[-2.  3.]
  [ 2.  2.]]

 [[-2.  0.]
  [-2.  1.]]

 [[ 2.  1.]
  [ 2.  0.]]]
(1.0, 2.0, 2.0, 1.0)
(0.0, -2.0, 2.0, 1.0)
(0.0, -2.0, 2.0, 1.0)
(1.0, 2.0, 2.0, 1.0)
(1.0, -2.0, 2.0, 1.0)
(1.0, -2.0, 2.0, 1.0)
(1.0, 2.0, 2.0, 1.0)
(1.0, 2.0, 2.0, 1.0)
(0.9999999836700847, 2.0, 2.0, 1.0000000081649576)
(1.6329915288628347e-08, -2.0, 2.0, 1.0000000081649576)
(1.6329915288628347e-08, -2.0, 2.0, 1.0000000081649576)
(0.9999999836700847, 2.0, 2.0, 1.0000000081649576)
(1.0000000081649576, -2.0, 2.0, 1.0000000081649576)
(1.0000000081649576, -2.0, 2.0, 1.0000000081649576)
(1.0000000081649576, 2.0, 2.0, 1.0000000081649576)
(1.0000000081649576, 2.0, 2.0, 1.0000000081649576)
(0.9999996734016943, 2.0, 2.0, 1.0000001632991529)
(3.2659830577256696e-07, -2.0, 2.0, 1.0000001632991529)
(3.2659830577256696e-07, -2.0, 2.0, 1.0000001632991529)
(0.9999996734016943, 2.0, 2.0, 1.0000001632991529)
(1.0000001632991529, -2.0, 2.0, 1.0000001632991529)
(1.0000001632991529

capi_return is NULL
Call-back cb_fcn_in___user__routines failed.


KeyboardInterrupt: 

In [ ]:
params.comm_table

NameError: name 'params' is not defined

In [ ]:
U = exactU(ham.HCoefs, ham.HTuples, 1)

In [ ]:
import numpy as np
from numpy import kron
from scipy.linalg import expm, norm

import CQS.util.IO as IO


def KHKtypeI(kCoefs, hCoefs, k, h):
    N = len(h[0])
    KHK = Nident(N)

    #First loop of K terms:
    K = expm(PauliSum(1j*kCoefs, k))
    KHK = KHK @ K

    #H terms
    for (term, co) in zip(h, hCoefs):
        KHK = KHK @ PauliExpUnitary(N, co, term)

    K = expm(PauliSum(-1j*kCoefs, k))
    KHK = KHK @ K
    return KHK


def PauliSum(coefficients, tuples):
    H = np.diag(np.zeros(2**len(tuples[0])))

    for (co, term) in zip(coefficients, tuples):
        print(co)
        print(term)
        H = H + IO.tuplesToMatrix(co, term)
    return H


In [ ]:
#KHK = KHKtypeI(params.kCoefs, params.hCoefs,
#params.cartan.k, params.cartan.h)
print((params.kCoefs, params.hCoefs))
KHKval = KHK(params.kCoefs, params.hCoefs, params.cartan.k, params.cartan.h)

(array([0.50861098, 0.50861098]), array([5.e-324, 5.e-324]))


In [ ]:
KHKval


array([[ 1.00000000e+00+0.e+000j,  2.30239523e-18+5.e-324j,
         1.20320040e-17+5.e-324j, -1.04961432e-17+0.e+000j],
       [ 1.90693440e-17+5.e-324j,  1.00000000e+00+0.e+000j,
        -4.71110688e-18+0.e+000j, -1.20320040e-17+5.e-324j],
       [ 1.20320040e-17+5.e-324j, -1.04961432e-17+0.e+000j,
         1.00000000e+00+0.e+000j, -2.30239523e-18+5.e-324j],
       [-4.71110688e-18+0.e+000j, -1.20320040e-17+5.e-324j,
        -1.90693440e-17+5.e-324j,  1.00000000e+00+0.e+000j]])

In [ ]:
U

array([[-3.84852853e-02+0.59665795j,  7.06115200e-17+0.35184491j,
         1.08789163e-17+0.35184491j, -5.78787591e-01-0.24481304j],
       [ 2.81552897e-17+0.35184491j, -3.84852853e-02-0.59665795j,
        -5.78787591e-01+0.24481304j, -4.77003567e-17+0.35184491j],
       [ 1.50926397e-17+0.35184491j, -5.78787591e-01+0.24481304j,
        -3.84852853e-02-0.59665795j,  1.77273529e-17+0.35184491j],
       [-5.78787591e-01-0.24481304j,  4.97853916e-17+0.35184491j,
         9.64493029e-18+0.35184491j, -3.84852853e-02+0.59665795j]])